### ISSUE TITLE
Move logo to external source

### ISSUE THREAD

**Issue by pavelkvasnikov** [pavelkvasnikov/endpoint-flux#8]
Move logo file from a gem repo. Any file storage or cloud provider is fine.

**Comment by ghost** [comment]
I can do this, but after moving it to a cloud provider, should I change it in places like README and other files? @pavelkvasnikov

**Comment by pavelkvasnikov** [comment]
@debugleader thanks for helping! Yeah, you need to move actual file somewhere and also update links to it. Currently it's only in ```README```

**Comment by debugleader** [comment]
Is it okay if I converted the SVG logo into a JPEG format?
Most of the websites I know and cloud providers don't allow SVG hosting formats.
@pavelkvasnikov

**Comment by pavelkvasnikov** [comment]
@debugleader it's ok, but prefer PNG over JPEG, don't forget to check image size

**Comment by ghost** [comment]
Done @pavelkvasnikov Actually SVG was fine.
